# The `talsim` package

## Imports and setup

In [1]:
import datetime
import logging
from pathlib import Path
import sys

import pandas as pd

# import the talsim package and the Timeseries class
# if necessary adjust `basedir` to point to the directory containing the `lib` directory
basedir = Path().absolute().parent
sys.path.append(str(basedir))

import talsimpy as talsim
from talsimpy import Timeseries

In [2]:
# setup logging to see log messages in the notebook
# create a console handler
ch = logging.StreamHandler()
ch.setLevel(logging.INFO)
# add formatters to the handler
ch.setFormatter(logging.Formatter('%(name)-12s %(levelname)-8s %(message)s'))
# config
logging.basicConfig(
    level=logging.NOTSET,
    handlers=[ch],
    force=True
)

## Simulating a dataset

In [3]:
# instantiate a dataset
tds = talsim.TalsimDataset(r"data/test_kal-faktor", "Test_KAL-Faktor")
tds

TalsimDataset 'Test_KAL-Faktor' in data\test_kal-faktor

In [ ]:
# instantiate an engine
path_engine = r"<path_to_talsim_engine>"
engine = talsim.TalsimEngine(f"{path_engine}")
engine

TalsimEngine in C:\data\Projekte\4.1.27

In [5]:
# check the engine version
engine.version

'4.1.27'

In [6]:
# simulate
engine.simulate(tds)

talsimpy.talsimengine INFO     Launching Talsim-NG v4.1.27...
talsimpy.talsimengine INFO     Simulation successful!

True

In [7]:
# check the warnings (works similarly for errors)
print(tds.warnings)

None

In [8]:
# check for timeseries result files
tds.timeseries_result_files

[WindowsPath('data/test_kal-faktor/Test_KAL-Faktor.WEL')]

In [9]:
# copy result files to a different directory
tds.copy_result_files(tds.path / "results")

talsimpy.talsimdataset INFO     Copying file Test_KAL-Faktor.MAX...
talsimpy.talsimdataset INFO     Copying file Test_KAL-Faktor.WMX...
talsimpy.talsimdataset INFO     Copying file Test_KAL-Faktor.BLZ...
talsimpy.talsimdataset INFO     Copying file Test_KAL-Faktor.log...
talsimpy.talsimdataset INFO     Copying file Test_KAL-Faktor.WELINFO...
talsimpy.talsimdataset INFO     Copying file Test_KAL-Faktor.WEL...

## Reading data from a dataset

In [10]:
tds = talsim.TalsimDataset(r"data/test_kal-faktor", "Test_KAL-Faktor")

In [11]:
# get all simulation options (from the ALL file) as a dictionary (only strings)
tds.get_sim_options()

{'VERSION': '1.2',
 'Caption': 'KAL_kf1_0.15_JGG_0.15',
 'Text1': '',
 'Text2': '',
 'Text3': 'batch-run, 12.06.2023 12:24:36',
 'SimMode': '2',
 'SimStart': '02.11.2020 00:00',
 'SimEnd': '30.07.2021 00:00',
 'SimStartZre': '',
 'UseCurrentDate': 'N',
 'TimeStep_min': '60',
 'TimeStep_month': 'N',
 'SimBlock': '13',
 'ViewTimeStep': '30',
 'StartKey': '',
 'KProgID': '2',
 'PreStartStep': 'd',
 'PreStartCount': '1',
 'ConnectedKProgID': '0',
 'TimeStepCount': '',
 'LoopCount': '',
 'QGeneration': 'TRUE',
 'UseSimStart': 'FALSE',
 'IsActive': 'J',
 'UrbanLoss': '1',
 'StartLoss': '100',
 'ChannelFlow': '100',
 'ReservoirFill': '100',
 'SoilMoisture': '100',
 'CntrlFunction': 'J',
 'ObjectiveFunction': 'N',
 'Expo': '0',
 'ErrGauge': '0',
 'ErrObjective': '0',
 'OptionEzgScsLoss': '0',
 'PsiEndScs': '1',
 'EflThreshold': '0',
 'MaxIteration': '2',
 'SoilInterconnected': '0',
 'TempElevationFactor': '0.6',
 'ApplyWindElevationCorrection': '1',
 'SoilEvaporationMode': '3',
 'Max': 'J',
 'Blz': 'J',
 'Prob': 'N',
 'Wel': 'J',
 'Csv': 'N',
 'Bin': 'N',
 'Ani': 'N',
 'Soil': '0',
 'Crop': '0',
 'Hru': '0',
 'Groundwater': '0',
 'Storage': '0',
 'OverviewOnly': 'N',
 'ResultEachTimeStep': '1',
 'Decimals': '3',
 'ResultForStates': '',
 'Optimize': 'N',
 'OptMode': '1',
 'StartMemo': '',
 'EndMemo': ''}

In [12]:
# get sim start and end (as datetime objects)
print(tds.sim_start)
print(tds.sim_end)

2020-11-02 00:00:00
2021-07-30 00:00:00

### Reading individual dataset files as pandas DataFrames

Some dataset files can be read as a pandas DataFrame (currently BOA, BOD, EFL, EZG). Not all file versions are supported though.

In [13]:
tds = talsim.TalsimDataset(r"data/test_kal-faktor", "Test_KAL-Faktor")

In [14]:
df_boa = tds.file_to_dataframe("BOA")
df_boa.head()

,ID,Soil,BD,Typ,WP,FK,GPV,kf,maxInf,maxKap,Bemerkkung
0,1,xxx,3,2,169.50,421.50,475.50,9.8750,19.750,0,Boden_1
1,2,xxx,3,2,179.50,360.00,426.00,8.5625,17.125,0,Boden_2
2,3,xxx,3,2,249.00,764.00,913.00,13.7500,27.500,0,Boden_3
3,4,xxx,3,2,144.64,269.73,350.55,8.1875,16.375,0,Boden_4
4,5,xxx,3,2,108.80,245.20,316.40,31.6670,63.333,0,Boden_5

In [15]:
df_bod = tds.file_to_dataframe("BOD")
df_bod.head()

,ID,anzsch,d1,boa1,d2,boa2,d3,boa3,d4,boa4,d5,boa5,d6,boa6,Bemerkung
0,1,1,1.10,2,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,Profil_1
1,2,1,0.75,3,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,Profil_2
2,3,1,0.45,4,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,Profil_3
3,4,1,0.50,1,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,Profil_4
4,5,1,2.00,5,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,Profil_5 D*

In [16]:
df_ezg = tds.file_to_dataframe("EZG")
df_ezg.head()

,Bez,KNG,AUnit,A,Vg,Ho,Hu,L,N_Datei,Evp_Kng,...,Abl_QBas,Abl_QGWt,Grun_Bas2_bool,Grun_Bas2,Grun_Beta,Schn_Kng,Schn_Abgabe,Schn_WaEquiva,Scale_Precip,CWR_Demand_bool
0,AB23,3,NaN,459.62,1.8,418.86,297.35,3327,2,2,...,SPBE,SPBE,1,199.45,0.5,0,NaN,NaN,1.025,0

In [17]:
df_efl = tds.file_to_dataframe("EFL")
df_efl.head()

,EZG,Gef,Flaeche,Bod_ID,Lnz_ID,Irr_ID,CN,SimType,Stream,ELevation,HRU_ID,Out_ID,Inlet,Outlet,Branch
0,AB23,15,0.99,2,3,NaN,NaN,2,0,0,0,0,0,0,0
1,AB23,15,1.45,3,3,NaN,NaN,2,0,0,0,0,0,0,0
2,AB23,15,2.85,7,2,NaN,NaN,2,0,0,0,0,0,0,0
3,AB23,15,3.16,9,1,NaN,NaN,2,0,0,0,0,0,0,0
4,AB23,15,3.20,10,3,NaN,NaN,2,0,0,0,0,0,0,0

## Manipulating a dataset

A dataset can be manipulated by setting simulation options and calibration parameters

In [18]:
tds = talsim.TalsimDataset(r"data/test_kal-faktor", "Test_KAL-Faktor")

In [19]:
# setting simulation options (ALL file)
options = {
    "SimStart": datetime.datetime(2020, 11, 2),
    "SimEnd": datetime.datetime(2021, 7, 30),
    "ResultForStates": "",
    "NonexistentOption": 574,
}

tds.set_sim_options(options)

talsimpy.talsimdataset WARNING  Option 'NonexistentOption' was not found in ALL file and could not be set!

In [20]:
# set calibration parameters (KAL file)
params = {
    "RetKonFakNat": 2,
    "RetKonFakInt": 1,
    "NFK": 1.4,
    "MAXINF": 10,
    "NonexistentParameter": "test",
}

tds.set_calibration_parameters(params)

talsimpy.talsimdataset WARNING  Parameter 'NonexistentParameter' was not found in KAL file and could not be set!

More possibilities for manipulating a dataset are provided by a template system:

* Template files must be named like the original file but with an additional extension "template", e.g. `dataset.EZG.template` and will replace the original file after template processing.
* Template files can contain placeholders for variables enclosed with curly braces, e.g. `{variable_name}`
* Placeholders can optionally contain a format specifier according to https://docs.python.org/3/library/string.html#format-specification-mini-language, examples:
  * `{variable_name:8.3f}` for a float with max length 8 and up to 3 decimal places
  * `{variable_name:>8}` for an integer or string, right-aligned and filled (or cut) to a total length of 8 characters
  * `{variable_name:%d.%m.%Y %H:%m}` for a datetime object
* The method `TalsimDataset.process_templates()` will process all the template files in a dataset by replacing placholders with values

In [21]:
# process template files
vars = {
    "variable_name": "value",
    "other_variable": 12345,
}
tds.process_templates(vars)

talsimpy.talsimdataset INFO     Processing templates in data\test_kal-faktor ...
talsimpy.talsimdataset INFO     Replacing variables in template file Test_KAL-Faktor.INFO.template...

## Additional methods

In [22]:
# calculate average soil properties over all layers
df_soil_avg = tds.calculate_average_soil_properties()
df_soil_avg.head()

   Bod_ID  WP_Average  FK_Average  GPV_Average
0       1      179.50      360.00       426.00
1       2      249.00      764.00       913.00
2       3      144.64      269.73       350.55
3       4      169.50      421.50       475.50
4       5      108.80      245.20       316.40

In [23]:
# this dataframe can be merged with that of the EFLs to obtain average soil properties per EFL
df_efl_soil_avg = pd.merge(df_efl, df_soil_avg, how="left", on="Bod_ID")
df_efl_soil_avg.head()

,EZG,Gef,Flaeche,Bod_ID,Lnz_ID,Irr_ID,CN,SimType,Stream,ELevation,HRU_ID,Out_ID,Inlet,Outlet,Branch,WP_Average,FK_Average,GPV_Average
0,AB23,15,0.99,2,3,NaN,NaN,2,0,0,0,0,0,0,0,249.00,764.00,913.00
1,AB23,15,1.45,3,3,NaN,NaN,2,0,0,0,0,0,0,0,144.64,269.73,350.55
2,AB23,15,2.85,7,2,NaN,NaN,2,0,0,0,0,0,0,0,169.50,421.50,475.50
3,AB23,15,3.16,9,1,NaN,NaN,2,0,0,0,0,0,0,0,93.30,184.80,243.50
4,AB23,15,3.20,10,3,NaN,NaN,2,0,0,0,0,0,0,0,116.45,242.64,314.09